name: Android Emulator

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      continue-on-error: false

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
      continue-on-error: false

    - name: Install Android tools and dependencies
      run: |
        sudo apt update
        sudo apt -y install android-tools-adb pulseaudio ffmpeg libsm6 libxext6 unzip
        wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
        unzip commandlinetools-linux-11076708_latest.zip
        rm -rf commandlinetools-linux-11076708_latest.zip
        sudo mv cmdline-tools /usr/lib/android-sdk/
        sudo ln -s /usr/lib/android-sdk/cmdline-tools /usr/lib/android-sdk/cmdline-tools/latest
        export ANDROID_HOME="/usr/lib/android-sdk"
        export ANDROID_SDK_ROOT="/usr/lib/android-sdk"
        yes | sdkmanager --licenses
        sdkmanager "system-images;android-35;google_atd;arm64-v8a"
        sdkmanager "platforms;android-35"
      continue-on-error: false

    - name: Create and start emulator
      run: |
        avdmanager create avd -n EmulatorTest -k "system-images;android-35;google_atd;arm64-v8a" -d "pixel_6_pro"
        emulator -avd EmulatorTest -no-window -no-audio -no-boot-anim -gpu swiftshader_indirect &
        adb wait-for-device
        adb shell input keyevent 82
      continue-on-error: false

    - name: Wait for emulator to start
      run: |
        adb wait-for-device
        adb shell getprop init.svc.bootanim | grep -m 1 stopped
      continue-on-error: false

    - name: Save emulator screenshot
      run: adb exec-out screencap -p > $GITHUB_WORKSPACE/emulator-screenshot.png
      continue-on-error: false

    - name: Upload screenshot to artifacts
      uses: actions/upload-artifact@v4.6.0
      with:
        name: emulator-screenshot
        path: $GITHUB_WORKSPACE/emulator-screenshot.png
      continue-on-error: false
